#Docker compose file to run sender container
sender:
    build: .
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        COLLECTOR_URL: http://localhost:8989/collector/metrics/ #Change this to the location of the collector
        DOCKER_API_VERSION: "1.20"
        #If this environment variable is set, the sender will pull metrics from cadvisor
        # CADVISOR_URL: http://localhost:8080/api/v1.2/ 
    container_name: sender